language: node_js
node_js:
  - "node"
install:
  - npm install -g mocha istanbul codecov
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
  - codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
